bestchains/bc-cli

.github/workflows/codecov.yaml, codecov.yaml
should enable `CodeCov` before merge this commit.
please @nkwangleiGIT
=> chore: add codecov action

cmd/bc-cli/delete/delete.go, cmd/bc-cli/main.go, go.mod, go.sum, pkg/account/create.go, pkg/account/delete.go, pkg/account/get.go, pkg/account/types.go, pkg/common/common.go, pkg/depository/get.go
feat: commands to manage wallet accounts
Fix: https://github.com/bestchains/bc-cli/issues/8
=> feat: commands to manage wallet accounts

pkg/depository/create.go
fix: 'ID' shorthand is more than one ASCII character
=> fix: 'ID' shorthand is more than one ASCII character

pkg/account/create_test.go, pkg/account/delete_test.go, pkg/account/get_test.go, pkg/account/types_test.go, pkg/depository/create.go
fix: add tests for the account command
=> fix: add tests for the account command

cmd/bc-cli/main.go, go.mod, go.sum, pkg/auth/auth.go, pkg/common/config.go, pkg/depository/get.go, pkg/utils/http/get.go
=> feat: add oidc auth

pkg/depository/create.go
=> fix: simplify the code

cmd/bc-cli/main.go, pkg/auth/auth.go, pkg/common/config.go
=> chore: simplify the code

cmd/bc-cli/get/get.go, pkg/chaincode/get.go, pkg/chaincodebuild/get.go, pkg/channel/get.go, pkg/common/ibp.go, pkg/federation/get.go, pkg/policy/get.go, pkg/proposal/get.go, pkg/vote/get.go
=> feat: add more get/list commands

.gitignore, cmd/bc-cli/create/create.go, go.mod, go.sum, pkg/account/account.go, pkg/account/create.go, pkg/account/create_test.go, pkg/account/delete.go, pkg/account/delete_test.go, pkg/account/get.go, pkg/account/get_test.go, pkg/account/wallet.go, pkg/account/wallet_test.go, pkg/common/common.go, pkg/common/config.go, pkg/depository/create.go, pkg/depository/create_test.go, pkg/depository/types.go, pkg/market/repository/create.go, pkg/market/repository/types.go, pkg/nonce/nonce.go, pkg/nonce/nonce_test.go
Changelogs:
1. Add new command market repo
2. refactor account & wallet management code
3. fix viper binding
=> feat: add market commands

cmd/bc-cli/get/get.go, pkg/common/ibp.go, pkg/federation/get.go, pkg/network/get.go
=> feat: get & list network

cmd/bc-cli/get/get.go, pkg/common/ibp.go, pkg/endorsepolicy/get.go
Fix: https://github.com/bestchains/bc-cli/issues/35
```shell
➜  bc-cli git:(ep) ✗ ./main get ep --network=proof-c0zpw
NAME            AGE
epolicy-7bu8o   10d
epolicy-bj4xw   45d
epolicy-tkeyx   44d
epolicy-toy3i   41d
```
=> feat: get endorsepolicy

cmd/bc-cli/get/get.go, pkg/chaincodebuild/get.go, pkg/common/ibp.go
=> feat: get & list chaincodeBuild

cmd/bc-cli/get/get.go, pkg/chaincode/get.go, pkg/common/ibp.go
Fix #34 
```shell
➜  bc-cli git:(a2fc395) ✗ ./main get chaincode --channel channel-z56ar         
NAME              AGE
chaincode-3bdbf   47d
chaincode-79t9d   48d
chaincode-9x3y4   48d
chaincode-d632u   48d
chaincode-g6vhr   48d
chaincode-l10c3   48d
chaincode-r1iu2   40d
➜  bc-cli git:(a2fc395) ✗ ./main get chaincode --channel channel-z56ar --id acl                 
NAME              AGE
chaincode-d632u   48d
chaincode-g6vhr   48d
chaincode-l10c3   48d
➜  bc-cli git:(a2fc395) ✗ ./main get chaincode --channel channel-z56ar --id acl --version v0.0.1
NAME              AGE
chaincode-d632u   48d
chaincode-g6vhr   48d
chaincode-l10c3   48d
```
=> feat: get & list chaincode

pkg/endorsepolicy/get.go
=> fix: fix typo

cmd/bc-cli/get/get.go, pkg/channel/get.go, pkg/common/ibp.go
=> feat: get & list channel

pkg/chaincode/get.go, pkg/chaincodebuild/get.go, pkg/depository/create.go, pkg/endorsepolicy/get.go, pkg/federation/get.go, pkg/market/repository/create.go, pkg/network/get.go, pkg/org/get.go, pkg/proposal/get.go
fix: add short description for some commands
=> fix: add short description for some commands

pkg/account/create.go, pkg/account/delete.go, pkg/account/get.go
=> chore: avoid command panic

pkg/depository/get.go
=> fix: Replace flag lang with flag certificateStyle when downloading certificates

go.mod, go.sum, pkg/depository/download.go, pkg/depository/get.go
feat: add download progress bar
```shell
root@macbookpro:~/workspace/bc-cli/cmd/bc-cli# ./main get depository --host='https://bc-saas.172.22.96.209.nip.io'
INDEX    KID                                         PLATFORM      OPERATOR                                      OWNER    BLOCKNUMBER    TIME
51       e13ac64442f6029370209f74a22cc9eb54444aca    bestchains    0x02624bfc011381aa1f4e19db60e3f46673f1f171             118            2023-06-26T18:01:33
50       02e853e0f68566e62fddd9c4e014db65b7f315d9    bestchains    0x02624bfc011381aa1f4e19db60e3f46673f1f171             117            2023-06-19T17:36:55
49       c406fdadec37faa9dfcc0cd64e9768d890cfbf44    bestchains    0x02624bfc011381aa1f4e19db60e3f46673f1f171             116            2023-06-19T17:35:15
48 …
```
=> feat: add download progress bar

pkg/chaincode/get.go, pkg/chaincodebuild/get.go, pkg/network/get.go, pkg/proposal/get.go
=> chaincode and chaincodebuild args de-duplication

Makefile, build/dockerfile.bc-cli, hack/lib/docker.sh
fix: fix binary file loss issue
=> fix: fix binary file loss issue
